server:
  port: 8089


spring:
 application:
  name: product-cart
 
## provide cloud config uri
 config:
  import: configserver:http://localhost:8888

eureka:
  client:
    service-url:
      default-zone: http://eureka-server