server:
  port: 8087
spring:
 application:
  name: product-inventory
  
# provide cloud config uri
 config:
  import: configserver:http://localhost:8888

eureka:
  client:
    service-url:
      default-zone: http://eureka-server