services:
 mysql:
  image: mysql:8
  container_name: mysqlcontainer
  ports:
   - "3307:3306"
  environment:
   MYSQL_ROOT_PASSWORD: root
  networks:
   - ecom-network
 
 product-catalog:
  build:
   context: ../ecom-productcatalog-service
   dockerfile: Dockerfile
  container_name: catalog-container
  ports:
  - "8084:8084"
  depends_on:
   - config-server
   - mysql
  networks:
     - ecom-network

 product-inventory:
  build:
   context: ../ecom-productinventory-service
   dockerfile: Dockerfile
  container_name: inventory-container
  ports:
   - "8087:8087"
  depends_on:
   - config-server
   - mysql
  networks:
   - ecom-network
 
 product-info:
    build:
     context: ../ecom-productinfo-service
     dockerfile: Dockerfile
    container_name: info-container
    ports:
     - "8082:8082"	
    networks:
     - ecom-network

 product-cart:
    build:
     context: ../ecom-productcart-service
     dockerfile: Dockerfile
    container_name: cart-container
    ports:
     - "8089:8089"	 
    depends_on:
     - config-server
     - mysql
    networks:
      - ecom-network

 config-server:
    build:
     context: ../ecom-config-server
     dockerfile: Dockerfile
    container_name: config-container
    ports:
     - "8888:8888"	
    networks:
     - ecom-network

networks:
   ecom-network:
    driver: bridge