server:
  port: 8084


message: In catalog service
#datasource specific properties
spring:
 application:
  name: product-catalog
 profiles:
    active: prod,dev
#  datasource:
#    username: root
#    password: root
#    url: jdbc:mysql://localhost:3306/ecomdb
##jpa properties
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
  
# provide cloud config uri
 config:
  import: configserver:http://localhost:8888

eureka:
  client:
    service-url:
      default-zone: http://eureka-server